### ISSUE TITLE
lapply on List returns list

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/S4Vectors#30] opened 2019-02-27 00:29 UTC
Shouldn't `S4Vectors::lapply()` return another S4 List, rather than a base list?

The current behavior is:
```
> library(S4Vectors) 
> a <- List(1) 
> class(S4Vectors::lapply(a, I)) 
[1] "list"
```

https://github.com/Bioconductor/S4Vectors/blob/b14a989db670382566500d025e49e15fbf46ac12/R/List-utils.R#L11

**Comment by lawremi** [comment] 2019-02-27 01:19
It returns list by design, because we view `lapply()` as a constructor of list, just like `list()`, arguing that the type of `X` has no bearing on the type of the return value. Long ago there was an `Lapply()` that returned a List, but we got rid of it, with the rationale that it would be more transparent to explicitly coerce the result of `lapply()` to a List with `as(x, "List")`.

**Comment by hpages** [comment] 2019-03-05 17:20
I don't remember `Lapply()` but we have `endoapply()` which enforces propagation of the input type:
```
X <- IntegerList(1:5, NULL, 2:-1)
endoapply(X, rev)
# IntegerList of length 3
# [[1]] 5 4 3 2 1
# [[2]] integer(0)
# [[3]] -1 0 1 2
```
Sometimes this enforcement is not what you want though:
```
endoapply(X, function(x) sprintf("ID%03d", x))
# IntegerList of length 3
# [[1]] <NA> <NA> <NA> <NA> <NA>
# [[2]] integer(0)
# [[3]] <NA> <NA> <NA> <NA>
# Warning message:
# In .as(from) : NAs introduced by coercion
```
In this case Michael's `as(lapply(...), "List")` is preferable:
```
as(lapply(X, function(x) sprintf("ID%03d", x)), "List")
# CharacterList of length 3
# [[1]] ID001 ID002 ID003 ID004 ID005
# [[2]] character(0)
# [[3]] ID002 ID001 ID000 ID-01
```
Note that it doesn't hurt to be a little more specific about the expected returned type:
```
as(lapply(X, function(x) sprintf("ID%03d", x)), "CharacterList")
```
I find that this makes the code slightly more readable/transparent.

**Comment by hpages** [comment] 2019-03-23 20:03
@lwaldron I'm closing the issue. Feel free to reopen if you want to further discuss this.

**Closed by hpages** 2019-03-23 20:03 UTC
